#pragma once
enum keyscreation { INITIAL_KEYS = 1};
enum registrationCodes { LOG_IN = 11, LOG_IN_SUCCESSFULLY, LOG_OUT, LOG_OUT_SUCCESSFULLY, REGISTRATION, SUCCESSFUL_REGISTRATION, SIGN_OUT, SIGN_OUT_SUCCESSFULLY};
enum loginCodes { SALT_REQUEST = 21, SUCCESSFUL_SALT_REQUEST, EXCHANGE_NEW_KEYS, EXCHANGE_NEW_KEYS_SUCCESSFUL, VERIFICATION_MESSAGE, SUCCESSFUL_VERIFICATION_FOR_MESSAGE};
enum ipCode{IP_REQUEST = 31, IP_REQUEST_FROM_PEER, IP_RESPONSE_FROM_PEER, IP_RESPONSE, CHECK_FOR_REQUEST, REQUEST_SENT_SUCCESSFULLY, CANCEL_REQUEST, CANCEL_REQUEST_SUCCESSFULLY, FINISHED};
enum listeningCode{LISTEN_REQUEST = 51, LISTEN_ACCEPTED, STOP_LISTENING, STOPPED_SUCCESSFULLY};
